name: micro_frontends_example

packages:
  - packages/**

scripts:
  android-wifi:
    description: Connect an Android device via Wifi
    run: |
      echo "Getting the IP address of the Android device..."
      IP=$(adb shell ip -f inet addr show wlan0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
      if [ -z "$IP" ]; then
          echo "Failed to obtain the IP address of the device. Ensure the device is connected via USB and USB debugging is enabled."
          exit 1
      fi
      
      echo "Enabling TCP/IP connection..."
      adb tcpip 5555
      sleep 2

      echo "Connecting to the device via Wi-Fi..."
      adb connect $IP:5555
      if adb devices | grep -q "$IP:5555"; then
          echo "Successfully connected to the device via Wi-Fi."
      else
          echo "Failed to connect to the device via Wi-Fi."
          exit 1
      fi

      adb devices
      echo "The device is ready for use."